version: "3.9"

services:
  backend:
    build: ./ethics_api
    container_name: ethics_backend
    ports:
      - "8000:8000"
    volumes:
      - ./ethics_api:/app
    env_file:
      - .env

  frontend:
    build: ./ethics-frontend
    container_name: ethics_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ethics-frontend:/app
      - /app/node_modules   # ‚Üê MUY IMPORTANTE

    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
